add complete full app
wisdomdevil/go_final_project pull request #1
Opened 2024-06-20 18:04 UTC by wisdomdevil

2024-06-21 18:12 UTC, just-musha requested changes
Привет!

Только добралась до твоей работы, и сразу попрошу написать небольшой README, как запустить сервер и тесты, где что прописать нужно. Это ускроит проверку.

И проверить создание таблицы, сейчас на старте так: 
```
2024/06/21 21:08:24 Check file existance /home/mbulatova/projects/yandex-homeworks/sprint-final/go_final_project-wisdomdevil/scheduler.db
2024/06/21 21:08:24 DB file /home/mbulatova/projects/yandex-homeworks/sprint-final/go_final_project-wisdomdevil/scheduler.db exists.
2024/06/21 21:08:24 Starting server on port: 7540
2024/06/21 21:09:15 err: SQL logic error: no such table: scheduler (1)
```

2024-06-21 18:12 UTC, just-musha commented on cmd/main.go
> +		os.Getenv("TODO_PASSWORD"),
Можно тут ещё какие-то дефолтные значения задать, если не указаны переменные

2024-06-29 09:05 UTC, wisdomdevil commented on cmd/main.go
> +		os.Getenv("TODO_PASSWORD"),
Привет, сделал дефолтные

2024-06-29 13:18 UTC, just-musha commented
@wisdomdevil Роман, привет! Подскажи, у тебя все тесты проходят локально?

2024-06-29 14:14 UTC, just-musha requested changes
Роман, привет! Спасибо за инструкцию.

1. У меня упали тесты, проверь что у тебя они проходят, или нужно внести правки. Это первое что необходимо сделать, если у тебя они падают. Падающие тесты - блокер для ревью, поэтому сначала нужно добиться чтоб они прошли
2. После того как тесты пройдут - оставила пачку правок по коду, для 1 итерации. Несколько правок нужно сделать сразу в нескольких местах - не стала дублировать комментарии - посмотри, где это будет необходимо.

2024-06-29 14:14 UTC, just-musha commented on tests/db_2_test.go
> -	id, err := res.LastInsertId()
Тесты не предполагается менять. Давай вернем обратно

2024-06-29 14:14 UTC, just-musha commented on README.md
> +- Удаление задач;
А что с правилами повторения, какие должны работать? Здесь лучше прям по заданиям перечислить, что реализовывал, чтобы сразу было понятно -  что искать и тестить.

Насколько вижу, есть также задание с переменными окружения, Докерфайл, авторизация, и поиск по дате и названию задачи.

2024-06-29 14:14 UTC, just-musha commented on cmd/main.go
> +	"github.com/go-chi/chi/v5"
Импорты должны быть разбиты на блоки - стандартные пакеты, внешние пакеты и отдельно внутрение. Вообще импорты сортирует `goimports`, но на блоки нужно разбить руками.

2024-06-29 14:14 UTC, just-musha commented on cmd/main.go
> +	"github.com/go-chi/chi/v5"
Это нужно проверить во всех файлах

2024-06-29 14:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +	}
Здесь нужно не забыть проверить ошибку `rows.Err`

2024-06-29 14:14 UTC, just-musha commented on internal/parser/parser.go
> +	if numDay == 7 {
Числа лучше вынести в константы, чтобы не оставлася magic number в коде

2024-06-29 14:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +		return s, err
Здесь лучше вернуть пустую стркутуру, тк произошла ошибка в процессе scan и мб в `s` данные битые

2024-06-29 14:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +	limitConst := 20
Повторяется в 2 местах, лучше вынести в константу

2024-06-29 14:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +	}
Нужно проверить rows.Err

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +	errorJson, _ := apiErr.ToJson()
Почему решил здесь скипнуть ошибку? Ошибки необходимо проверять и обрабатывать

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +	http.Error(w, string(errorJson), status)
Этот вызов отправляет ответ, что не соответствует названию функции RenderApiError - получается не только рендер. Можно эту строчку отсюда вынести?

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +func (a *Api) TaskHandler(w http.ResponseWriter, r *http.Request) {
Как насчет разбить на отдельные хендлеры, для каждого типа запроса?

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +		RenderApiError(w, fmt.Errorf(ResponseWriteError), http.StatusBadRequest)
Тут не нужно отправлять ошибку. Достаточно будет просто залогировать

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +		RenderApiError(w, fmt.Errorf(ResponseWriteError), http.StatusBadRequest)
(и в других аналогичных местах с вызовом `Write`)

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +		RenderApiError(w, fmt.Errorf(MarshallingError), http.StatusBadRequest)
Не смогли смаршалить - это внутренняя ошибка сервера (посмотри плиз по коду, есть ли ещё похожие места где нужно поправить)

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +	} else {
Тут можно упростить и обойтись без `else` 

```
if err != nil {

}
w.WriteHeader(http.StatusOK)
WriteResponse(w, []byte("{}"))
```

2024-06-29 14:14 UTC, just-musha commented on internal/handlers/handlers.go
> +	} else {
И тут можно без `else`

2024-06-29 19:45 UTC, wisdomdevil commented on tests/db_2_test.go
> -	id, err := res.LastInsertId()
Если поправить, то линтер ругается на то, что ошибку не обрабатывают далее. Стоит этот вопрос адресовать к создателям курса

tests/db_2_test.go:50:6: ineffectual assignment to err (ineffassign)
        id, err := res.LastInsertId()
            ^

2024-06-29 20:05 UTC, wisdomdevil commented on README.md
> +- Удаление задач;
Readme дополнил, но пожалуйста просьба так сильно к нему не придираться, это воля фантазии :) Кажется максимально инструкции я в нем описал и возможности аппликухи тоже

2024-06-29 20:05 UTC, wisdomdevil commented on cmd/main.go
> +	"github.com/go-chi/chi/v5"
Разбил

2024-06-29 20:05 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
> +	}
сделал

2024-06-29 20:05 UTC, wisdomdevil commented on internal/parser/parser.go
> +	if numDay == 7 {
Вынес в константы

2024-06-29 20:06 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
> +		return s, err
Вернул пустую структуру

2024-06-29 20:06 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
> +	limitConst := 20
вынес в константу

2024-06-29 20:06 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
> +	}
сделал проверку

2024-06-29 20:06 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +	errorJson, _ := apiErr.ToJson()
Обработал

2024-06-29 20:07 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +	http.Error(w, string(errorJson), status)
Так как функция вызывается 43 раза и разбивать не сильно хотелось, заняло бы тонну времени. Переименовал функцию, теперь она называется RenderApiErrorAndResponse

2024-06-29 20:07 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +func (a *Api) TaskHandler(w http.ResponseWriter, r *http.Request) {
Разбил на хендлеры по каждому методу

2024-06-29 20:07 UTC, just-musha commented
@wisdomdevil попробуй ещё снести файл БД и запустить тесты. Предалагаю чекнуть создание таблицы в тестах

UPD: все ок, тесты проходят. Рекомендация снести файл помогла мне самой

2024-06-29 20:07 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +		RenderApiError(w, fmt.Errorf(ResponseWriteError), http.StatusBadRequest)
Сделал

2024-06-29 20:08 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +		RenderApiError(w, fmt.Errorf(MarshallingError), http.StatusBadRequest)
Вот тут момент спорный, в твоем комменте - да, согласен. По остальным пробежался, поправил в каких считал нужным. Если тебе какие-то статусы кажутся неверными, напиши пожалуйста здесь плиз

2024-06-29 20:08 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +	} else {
сделано

2024-06-29 20:08 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +	} else {
готово

2024-06-29 20:12 UTC, just-musha commented on README.md
> +- Удаление задач;
Ок, да, инфы достаточно. Спасибо.

2024-06-30 12:14 UTC, just-musha requested changes
Привет! Посмотрела ещё раз, оставляю комменты по 2 итерации. 

Точно стоит поправить момент с Fatal, и по разбиению на файлы - обычно струкртура и её методы в отдельном файле - посмотри как получится разбить, есть файлы где несколько структур объявлено, это усложняет понимание что где

2024-06-30 12:14 UTC, just-musha commented on internal/config/config.go
> +		apiPort = "7540"
`const defaultPort` ?

2024-06-30 12:14 UTC, just-musha commented on internal/config/config.go
> +	DefaultPassword = "123456"
нужно ли экспортировать? используется только внутри пакета
```diff
-DefaultPassword
+defaultPassword
```

2024-06-30 12:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +	dt, err := time.Parse("20060102", t.Date)
Шаблон даты можно вынести в константу

2024-06-30 12:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +type DateSearchParam struct {
Это нужно в отдельный файл вынести - структуру и методы

2024-06-30 12:14 UTC, just-musha commented on internal/db/repo/scheduler.go
repo.go

2024-06-30 12:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +func (tr TasksRepository) UpdateTaskInBd(t models.Task) error {
```diff
-UpdateTaskInBd
+UpdateTask
```

2024-06-30 12:14 UTC, just-musha commented on internal/parser/parser.go
> +	if next > 0 && next <= 400 {
Другие числа в константы тоже лучше вынести, это считается хорошей практикой, и облегчает понимание при чтении кода

2024-06-30 12:14 UTC, just-musha commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
тут `return` не потерялся?

2024-06-30 12:14 UTC, just-musha commented on internal/handlers/handlers.go
> +type Api struct {
Я бы предложила вынести в файл api.go - структуру и её методы

2024-06-30 12:14 UTC, just-musha commented on internal/handlers/handlers.go
> +		log.Fatalf("Can not write response: %s", err.Error())
Это не должен быть Fatal, сервер стопнется - нам это не надо, достаточно залогировать как сообщение

2024-06-30 12:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +func (tr TasksRepository) PostTaskDone(id int) (*models.Task, error) {
(как рекомендация)

Этот метод использует готовые методы репозитория. Его можно было бы убрать с этого уровня и перенести выше - (обычно между db и handlers бывает ещё прослойка типа service, можно было бы туда). Или к мб к хендлерам, в твоем случае

2024-06-30 12:14 UTC, just-musha commented on internal/db/repo/scheduler.go
> +func (tr TasksRepository) PostTaskDone(id int) (*models.Task, error) {
Смысл в том что repo - это обертка над БД, там по сути ток запросы. А логика уже идет выше, в service уровне

2024-06-30 12:14 UTC, just-musha commented on tests/db_2_test.go
> -	id, err := res.LastInsertId()
Отправила авторам. Спасибо!

2024-06-30 18:43 UTC, wisdomdevil commented on internal/config/config.go
> +		apiPort = "7540"
Готово

2024-06-30 18:43 UTC, wisdomdevil commented on internal/config/config.go
> +	DefaultPassword = "123456"
готово

2024-06-30 18:45 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
> +	dt, err := time.Parse("20060102", t.Date)
готово

2024-06-30 18:46 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
> +func (tr TasksRepository) UpdateTaskInBd(t models.Task) error {
готово

2024-06-30 18:47 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
поправил

2024-06-30 18:50 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +		log.Fatalf("Can not write response: %s", err.Error())
готово

2024-06-30 18:59 UTC, wisdomdevil commented on internal/db/repo/scheduler.go
готово

2024-06-30 19:06 UTC, wisdomdevil commented on internal/handlers/handlers.go
> +type Api struct {
вынес

2024-06-30 19:08 UTC, wisdomdevil commented on internal/parser/parser.go
> +	if next > 0 && next <= 400 {
готово

2024-06-30 20:45 UTC, just-musha approved these changes
Поздравляю! Финальный проект принят! 

Проделана была приличная работа, много всего из курса получислось применить здесь - докер, пайплайн, репозиторий и работу с бд, реализацию апи. Отдельный респект за качественное описание проекта и выполнение доп.заданий! 

Успехов дальше в Го разработке!

2024-06-30 22:29 UTC, merged